# Generated by Django 5.2.6 on 2025-09-18 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thoi_gian_tao_don', models.DateTimeField(default=django.utils.timezone.now)),
                ('ma_don_hang', models.CharField(max_length=10)),
                ('ma_khach_hang', models.CharField(max_length=9)),
                ('khach_hang', models.TextField()),
                ('ma_pkkh', models.CharField(max_length=3)),
                ('mo_ta_pkkh', models.TextField()),
                ('ma_nhom_hang', models.CharField(max_length=4)),
                ('ten_nhom_hang', models.TextField()),
                ('ma_mat_hang', models.CharField(max_length=8)),
                ('ten_mat_hang', models.TextField()),
                ('don_gia', models.IntegerField()),
                ('so_luong', models.IntegerField()),
                ('thanh_tien', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='NhomHang',
            fields=[
                ('ma_nhom_hang', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ten_nhom_hang', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nhóm hàng',
            },
        ),
        migrations.CreateModel(
            name='PhanKhucKhachHang',
            fields=[
                ('ma_pkkh', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('mo_ta_pkkh', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Phân khúc khách hàng',
            },
        ),
        migrations.CreateModel(
            name='MatHang',
            fields=[
                ('ma_mat_hang', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ten_mat_hang', models.CharField(max_length=100)),
                ('don_gia', models.IntegerField()),
                ('ma_nhom_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.nhomhang')),
            ],
            options={
                'verbose_name_plural': 'Mặt hàng',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_khach_hang', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('phan_khuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.phankhuckhachhang')),
            ],
            options={
                'verbose_name_plural': 'Khách hàng',
            },
        ),
    ]
